### ISSUE TITLE
game keeps crashing as soon as I load game file

### ISSUE THREAD

**Issue by Suli2004** [Pixelguin/P4G-CEP-v13#13]
**Describe the problem**
I defeated the teddie shadow and followed the story right up until the point where it asks me to save. As soon as I pressed save the game crashed. Now whenever I try to load the game it goes straight to that save and crashes instantly. I was saving regularly and my last save is just before the boss fight so it won't take me long to get back to that point, however I don't want it to crash again. Thanks

**How to reproduce**
* I simply played the game and it crashed
* Now it crashes as soon as the file is loaded

I am unable to grab a screen shot but the error message simply says "Application has crashed"

**Comment by Pixelguin** [comment]
* First, try running the game without mods by launching it directly through Steam. If the game doesn't crash, overwrite the broken save right away. If the game still crashes, it's not an issue with mods.
* If the game is still crashing without mods, you can find your save data at `(Steam-folder)\userdata\(steamID3)\1113000\remote\`. If you know the save slot you used, delete the associated BIN and BINSLOT file. If you don't know, back up the `remote` directory and try deleting saves (BIN + BINSLOT) one by one, starting with the one with the most recent **Last modified** value.

**Comment by Suli2004** [comment]
* So I followed you steps and it crashed with steam aswell. So I deleted the save slot (slot 5) in the steam folder and reopened p4g and loaded the last save, but for some reason it's still showing save slot 5.

**Comment by Pixelguin** [comment]
That's because the game uses a global save that tracks that information and stores it in a different file. If you were able to load the game, save over slot 5 immediately and hopefully that does the trick.

**Comment by Suli2004** [comment]
wait how do I do that sorry?

**Comment by Pixelguin** [comment]
Just load the game on a different save and use that save point again on slot 5.

**Comment by Pixelguin** [comment]
@Suli2004 Is your problem solved?
