### ISSUE TITLE
reloaded.exe disappearing when launching game

### ISSUE THREAD

**Issue by zenganthefool** [Pixelguin/P4G-CEP-v13#14]
i wanted to try playing with mods for the first time (i have never touched persona 4 golden mods before) and i found the CEP on nexusmods website. I followed the guide step by step (at least as far as i'm aware) and once i was done, i made a shortcut on my desktop through the reloaded app in order to launch the game. However, as soon as i clicked on the shortcut to launch it, a command-like window opened up, lots of text appeared for a few seconds, then it disappeared, along with the modded p4g shortcut, and the reloaded.exe file in the mods folder. I don't know if anything else disappeared, but that's what i noticed. Now i'm not really sure if i have to do the whole process again, and even if i did, i don't know how to prevent it from just disappearing again. Does anyone know what happened?

**Comment by Pixelguin** [comment]
Your antivirus probably munched Reloaded II, but we can prevent it from happening again.

* Delete your current **P4G Mods** folder.
* Redownload P4G CEP and move your **P4G Mods** folder again, but don't launch Reloaded II yet!
  * You don't need to install the prerequisites again.
* [Add an exception in your antivirus software](https://p4g.cep.one/appendix/troubleshooting#how-do-i-add-an-exception-for-a-folder-in-my-antivirus-software) for your **.Reloaded II** folder.

After that, you should be able to use Reloaded II without it getting spontaneously deleted.

**Comment by Pixelguin** [comment]
@zenganthefool Is your problem solved?
