### ISSUE TITLE
Unknown Hard Error + Failed to encounter bgm pattern

### ISSUE THREAD

**Issue by ghost** [Pixelguin/P4G-CEP-v13#3]
**Describe the problem**
When pressing "Launch Application" on Reloaded II, the game won't start and displays an error message saying "Unknown Hard Error" after trying to load the music enhancement mod.

When the music enhancement mod is "turned off" it results in another error, where it says it "failed to encounter bgm pattern".

**How to reproduce**
* Press the launch button in Reloaded II

**Screenshots and files**
![image](https://github.com/Pixelguin/P4G-CEP-v13/assets/145328368/78351514-a111-43ff-9866-8b06cf2b1d0d)
![image](https://github.com/Pixelguin/P4G-CEP-v13/assets/145328368/b32ea58b-dac7-4190-8dc5-d6620008d3d6)

**Comment by Pixelguin** [comment]
Could I see the full log file? You can access previous logs by clicking this option in Reloaded II.

![image](https://github.com/Pixelguin/P4G-CEP-v13/assets/11445611/7ccfc443-e623-4b64-bcfe-167e6a3eae06)

**Comment by LenXR** [comment]
[2024-06-09 15.19.21 ~ P4G.txt](https://github.com/user-attachments/files/15753105/2024-06-09.15.19.21.P4G.txt)
here's the most recent one

**Comment by Pixelguin** [comment]
Sorry, we don't support pirated copies of the game. Pirated copies are the old **32-bit** version of the game which will not work with **64-bit** mods.
