### ISSUE TITLE
Invalid program: Attemped to call a UnmanagedCallersOnly method from managed code

### ISSUE THREAD

**Issue by thiviscar** [Pixelguin/P4G-CEP-v13#5]
**Describe the problem**
I'm not able to play the version 13.1 of P4G Community Enhancement, I've downloaded the game from Steam today, along with the newest version of the pack and followed the tutorial, but the game keeps giving the same error. I took a screenshot of the error and attached it along with a crash dump

**How to reproduce**
* 1) Download the version 13.1;
* 2) Follow the tutorial up to Final Steps;
* 3) Create Desktop shortcut and execute it as admin;
* 4) A cmd window opens and tries to open the game, but shows error instead.

**Screenshots and files**

![UnmanagedCallersOnly](https://github.com/user-attachments/assets/87db040a-a2ff-4459-a1af-0a7150bdde16)
[2024-07-23 21.43.52 ~ P4G.txt](https://github.com/user-attachments/files/16354592/2024-07-23.21.43.52.P4G.txt)

**Comment by thiviscar** [comment]
I tried disabling the Better Quizzes mod, but the same error happens for each mod in the Tweaks category, so I disabled them all, but it keeps giving the same error in the Music Enhancement Pack:
![2nd error](https://github.com/user-attachments/assets/fe0c5db1-9d02-4bb9-a11a-bb49cb6dc17c)
But, if I do disable Music Enhancement Pack, it gives me a new error:
![3rd error](https://github.com/user-attachments/assets/66215b85-f0c8-49a2-a2d2-c678c707a745)

**Comment by Pixelguin** [comment]
I'm not able to reproduce your error.
Try [adding an exception for your **P4G Mods** folder in your antivirus software.](https://p4g.cep.one/appendix/troubleshooting#how-do-i-add-an-exception-for-a-folder-in-my-antivirus-software)
