### ISSUE TITLE
Access to the path 'AppConfig.json' is denied

### ISSUE THREAD

**Issue by BuckOverwick** [Pixelguin/P4G-CEP-v13#7]
I'm really interested in trying this mod out but for some reason i keep getting this error when i try to set the file path to P4G.exe

![Screenshot 2024-08-10 090039](https://github.com/user-attachments/assets/d73985c7-580b-4275-9add-b7a979313edb)
![Screenshot 2024-08-10 090057](https://github.com/user-attachments/assets/4b7c2e7c-b629-476a-aae6-a916db473762)

Please help me out, I've been suffering for an hour trying to fix this.

**Comment by BuckOverwick** [comment]
I've already tried adding an exception for my P4G Mods folder in my antivirus software (Windows Defender)

**Comment by Pixelguin** [comment]
Please upload a log file.
* Launch Reloaded II and select **View Log Files**.
![image](https://github.com/user-attachments/assets/9546cbe3-8f93-4a4d-b316-bddebf9c9b76)
* A File Explorer window will open. Sort it by **Date modified** and upload the latest log for P4G here.

**Comment by BuckOverwick** [comment]
[2024-08-09 09.55.43 ~ P4G.txt](https://github.com/user-attachments/files/16567920/2024-08-09.09.55.43.P4G.txt)

**Comment by Pixelguin** [comment]
Your **P4G Mods** folder is in your Downloads folder and needs to be moved somewhere else as described [here](https://p4g.cep.one/install/download-and-prepare#copy-p4g-mods-folder).

It looks like you already have a place ready to go in **C:\P4G Mods**, so use that location.

**Comment by BuckOverwick** [comment]
I'm pretty sure it's already in **C:\P4G Mods**.
![Screenshot 2024-08-10 105748](https://github.com/user-attachments/assets/ee54f5a3-bc6a-4515-a993-6dbb9cd4c46a)
![image_2024-08-10_105943362](https://github.com/user-attachments/assets/1c586f8a-c257-4762-8633-6e7eb4de38b3)

**Comment by Pixelguin** [comment]
Are you sure you're uploading the most recent log file? Try launching the game again to generate a new one.

I can't think of any other reason AppConfig.json access would be denied other than OneDrive or some other cloud sync program trying to access it at the same time as Reloaded II.

**Comment by BuckOverwick** [comment]
That's another problem, the game won't even start no matter how many times I click the 'Launch Application' button. It only started one time when i first installed everything.

**Comment by Pixelguin** [comment]
That's very strange. I would try redownloading P4G CEP and starting the installation process over,.

**Comment by BuckOverwick** [comment]
Ok thank god I fixed AppConfig.json being denied access, I had to go into the individual properties of the files and allow guest access, which fixed it somehow. Thank you for the support, sorry for taking so much of your time. 

One last question, should I enable these 2 mods:
![image_2024-08-10_115415359](https://github.com/user-attachments/assets/962e86c0-537f-47c0-a622-b553479d8cee)

**Comment by BuckOverwick** [comment]
Also is P4 Fog Restoration https://gamebanana.com/wips/86080 compatible?

**Comment by Pixelguin** [comment]
> One last question, should I enable these 2 mods:

Those are empty dividers used for keeping the mod loader organized. Enabling them won't do anything.

> Also is P4 Fog Restoration compatible?

It should be as long as you follow the directions on that mod's page:
> Set your contrast setting in-game to 2 for the best experience!
> No TV Static+ should be placed **below** P4 Fog Restoration.
