### ISSUE TITLE
Always requires restart

### ISSUE THREAD

**Issue by TheRealSunaris** [Pixelguin/P4G-CEP-v13#8]
Reloaded seems to always require a computer restart to properly launch. 
I receive an "Unknown Error" of: _Failed to obtain port for the Reloaded instance running inside the process._

The last few entries in Reloaded are:
Starting FileEmulationFramework
[R-II SteamHook] SteamAPI_RestartAppIfNecessary hooked successfully.
[Reloaded] - LoadTime: 43ms
[R-II SteamHook] SteamAPI_IsSteamRunning hooked successfully.

Reloaded ver: 1.27.12
.NET ver: 8.0.7
CEP ver: 13.2   (updated Aug. 19th)

**Comment by Pixelguin** [comment]
The next time this happens, check in Task Manager if P4G.exe is already running and end the task if it is. This can happen on some PCs, especially if you like to quit the game using Alt + F4.

A log file would be helpful as well:
* Launch Reloaded II and select **View Log Files**.
![image](https://github.com/user-attachments/assets/9546cbe3-8f93-4a4d-b316-bddebf9c9b76)
* A File Explorer window will open. Sort it by **Date modified** and upload the latest log for P4G here.

**Comment by TheRealSunaris** [comment]
[2024-08-22 20.41.31 ~ P4G.txt](https://github.com/user-attachments/files/16717437/2024-08-22.20.41.31.P4G.txt)

Here's the full log file. I don't normally quit by Alt-F4, sometimes but rarely. The error happens immediately after a normal quit.
Verified that the P4G.exe task isn't running.

I'm also using a desktop shortcut, created by Reloaded, but the same error happens if launching from Reloaded itself.
P4G will also launch normally without mods, but launching and closing down does not resolve the issue. I've also tried exiting Steam and restarting too.

**Comment by Pixelguin** [comment]
Hmm, I'm not 100% sure what it could be then. Try following the instructions for [adding an antivirus exception](https://p4g.cep.one/appendix/troubleshooting#how-do-i-add-an-exception-for-a-folder-in-my-antivirus-software) and let me know if that does the trick.
