### ISSUE TITLE
failed to load Reloaded-II

### ISSUE THREAD

**Issue by cath7ARSE** [Pixelguin/P4G-CEP-v13#9]
Trying to launch, I get the Following error

`Fatal error. Invalid program: attempted to call a UnmangedCallersOnly method from managed
Fatal error while logging another fatal error
Fatal error while logging another fatal error`
log below 
[Log 1 {2024-08-23 16.03.10 ~ P4G}.txt](https://github.com/user-attachments/files/16731079/Log.1.2024-08-23.16.03.10.P4G.txt)

I disable music enhancement pack and I get the following
![image](https://github.com/user-attachments/assets/e7295a03-ba19-495d-803f-440d29fa7f0c)
![image](https://github.com/user-attachments/assets/77a4441b-7981-446a-8df5-559bda4cb822)
![image](https://github.com/user-attachments/assets/3a16fa4f-d69a-47b5-9ee0-7a5bb76a2261)
log below 
[Log 2{2024-08-23 16.05.05 ~ P4G}.txt](https://github.com/user-attachments/files/16731126/Log.2.2024-08-23.16.05.05.P4G.txt)

with the 2nd instance the first attempt persona launched without mods and further attempts do not launch the game

**Comment by Pixelguin** [comment]
Sorry, we don't support pirated copies of the game.

Pirated copies are the old **32-bit** version of the game which will not work with **64-bit** mods.
